coverage exclude -scope /test_bench/dut/u_tcr -togglenode {tcr[2]} {tcr[3]} {tcr[4]} {tcr[5]} {tcr[6]} {tcr[7]} {tcr[12]} {tcr[13]} {tcr[14]} {tcr[15]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_tcr -togglenode {tcr[16]} {tcr[17]} {tcr[18]} {tcr[19]} {tcr[20]} {tcr[21]} {tcr[22]} {tcr[23]} {tcr[24]} {tcr[25]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_tcr -togglenode {tcr[26]} {tcr[27]} {tcr[28]} {tcr[29]} {tcr[30]} {tcr[31]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_cnt_ctrl -togglenode {thcsr[2]} {thcsr[3]} {thcsr[4]} {thcsr[5]} {thcsr[6]} {thcsr[7]} {thcsr[8]} {thcsr[9]} {thcsr[10]} {thcsr[11]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_cnt_ctrl -togglenode {thcsr[12]} {thcsr[13]} {thcsr[14]} {thcsr[15]} {thcsr[16]} {thcsr[17]} {thcsr[18]} {thcsr[19]} {thcsr[20]} {thcsr[21]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_cnt_ctrl -togglenode {thcsr[22]} {thcsr[23]} {thcsr[24]} {thcsr[25]} {thcsr[26]} {thcsr[27]} {thcsr[28]} {thcsr[29]} {thcsr[30]} {thcsr[31]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_interrupt -togglenode {tim_prdata[1]} {tim_prdata[2]} {tim_prdata[3]} {tim_prdata[4]} {tim_prdata[5]} {tim_prdata[6]} {tim_prdata[7]} {tim_prdata[8]} {tim_prdata[9]} {tim_prdata[10]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_interrupt -togglenode {tim_prdata[11]} {tim_prdata[12]} {tim_prdata[13]} {tim_prdata[14]} {tim_prdata[15]} {tim_prdata[16]} {tim_prdata[17]} {tim_prdata[18]} {tim_prdata[19]} {tim_prdata[20]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_interrupt -togglenode {tim_prdata[21]} {tim_prdata[22]} {tim_prdata[23]} {tim_prdata[24]} {tim_prdata[25]} {tim_prdata[26]} {tim_prdata[27]} {tim_prdata[28]} {tim_prdata[29]} {tim_prdata[30]} -comment {Reserved bit. Toggle is impossible.} 
coverage exclude -scope /test_bench/dut/u_interrupt -togglenode {tim_prdata[31]} -comment {Reserved bit. Toggle is impossible.} 
